-- Academic Relay
-- PostgreSQL schema for Supabase

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL DEFAULT 'student' CHECK (
        user_type IN ('student', 'faculty', 'admin')
    ),
    full_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMP
);

CREATE TABLE student_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    school_name VARCHAR(255),
    grade_level VARCHAR(50),
    academic_interests TEXT,
    bio TEXT
);

CREATE INDEX idx_student_profiles_user_id ON student_profiles (user_id);

CREATE TABLE faculty_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    department VARCHAR(255),
    university VARCHAR(255),
    research_interests TEXT,
    bio TEXT,
    profile_picture VARCHAR(255)
);

CREATE INDEX idx_faculty_profiles_user_id ON faculty_profiles (user_id);

CREATE TABLE circulars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    audience VARCHAR(100) NOT NULL,
    priority VARCHAR(20) DEFAULT 'medium',
    valid_until DATE,
    attachment VARCHAR(500),
    date_posted TIMESTAMP NOT NULL,
    posted_by VARCHAR(100) NOT NULL,
    posted_by_id INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    branch VARCHAR(50) NOT NULL,
    semester INTEGER NOT NULL,
    subject VARCHAR(100) NOT NULL,
    total_questions INTEGER DEFAULT 5,
    deadline DATE NOT NULL,
    total_marks INTEGER DEFAULT 100,
    attachment VARCHAR(500),
    created_by VARCHAR(100) NOT NULL,
    created_by_id INTEGER,
    date_posted TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (
        status IN ('active', 'expired')
    )
);

CREATE TABLE internal_marks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pin VARCHAR(20) NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    branch VARCHAR(50) NOT NULL,
    semester INTEGER NOT NULL,
    subject_code VARCHAR(20) NOT NULL,
    subject_name VARCHAR(255) NOT NULL,
    marks_obtained INTEGER DEFAULT 0,
    max_marks INTEGER DEFAULT 30,
    uploaded_by VARCHAR(100),
    uploaded_by_id INTEGER,
    date_uploaded TIMESTAMP NOT NULL
);

CREATE INDEX idx_internal_marks_pin ON internal_marks (pin);

CREATE TABLE study_materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    filename VARCHAR(500) NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    file_size INTEGER,
    file_type VARCHAR(100),
    branch VARCHAR(50) NOT NULL,
    semester INTEGER,
    subject_code VARCHAR(50),
    subject_name VARCHAR(255),
    uploaded_by VARCHAR(100),
    uploaded_by_id INTEGER,
    date_uploaded TIMESTAMP NOT NULL,
    download_count INTEGER DEFAULT 0
);

CREATE INDEX idx_study_materials_branch ON study_materials (branch);

CREATE INDEX idx_study_materials_semester ON study_materials (semester);

CREATE INDEX idx_study_materials_subject_code ON study_materials (subject_code);